apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  annotations:
    "helm.sh/resource-policy": keep  # Prevents deletion on `helm uninstall`
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi